### ISSUE TITLE
Feature: Add Trello API integration

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/LD-Cool-P#119]
Now that most backend pieces are in order, it's time to explore using the Trello API integration for improve workflow with automation.

Exploration/testing should include:
1. Creating a new card based on the template
2. Filling in the metadata information
3. Marking items as they are completed
4. Adding labels where appropriate

**Comment by zoidy** [comment]
Items 1, 2 and 4 are already taken care of with Trello automation and an external micro service running as a Google Script. Item 3 is not deemed desirable at this time as it couples LD-Cool-P with the Trello workflow too tightly. Closing
